
// Very much subject to changes
export const MessageTypes = {
  ADDPLAYER: 'ADDPLAYER',
  READYAPLAYER: 'READYAPLAYER',
  UPDATESETTINGS: 'UPDATESETTINGS',
  INITGAME: 'INITGAME',
  SUBMITWORDS: 'SUBMITWORDS',
  SETTEAMS: 'SETTEAMS',
  SETPLAYERS: 'SETPLAYERS',
  UPDATECONTROLLER: 'UPDATECONTROLLER',
  STARTROUND: 'STARTROUND',
  TOPAGE: 'TOPAGE',
  ENDROUND: 'ENDROUND',
  NEXTTURN: 'NEXTTURN',
  SERVERROOMCODE: 'SERVERROOMCODE',
  NEWROUNDSTAT: 'NEWROUNDSTAT'
}
